### ISSUE TITLE
UniversalStacktrace does not work with musl libc

### ISSUE THREAD

**Issue by ahesford** [MisterTea/UniversalStacktrace#1]
The `ust.hpp` header file includes `execinfo.h`, which defines `backtrace` and `backtrace_symbols`. On musl libc, the header (and therefore these function declarations) are not available.

**Comment by MisterTea** [comment]
What does musl provide instead?

**Comment by ahesford** [comment]
I'm not a musl user, but I was interested in updating your `EternalTerminal` project for Void Linux and need to be able to build this on several architectures with both glibc and musl. As of five years ago, it looks like there was no interest in supporting these capabilities natively: [https://www.openwall.com/lists/musl/2015/04/09/3](https://www.openwall.com/lists/musl/2015/04/09/3).

I don't know which `libbacktrace` is referred to in that message; the top [Duck Duck Go hit for libbacktrace](https://github.com/ianlancetaylor/libbacktrace) is too new and has a different interface.

There is also a [Boost interface](https://www.boost.org/doc/libs/1_65_1/doc/html/stacktrace/reference.html#header.boost.stacktrace.stacktrace_hpp) for implementing stack traces.

**Comment by ahesford** [comment]
Turns out there is an external `libexecinfo`, which you already use in `EternalTerminal` for the BSDs. This is a non-issue here.
